#!/usr/bin/env bats

load ../../../helpers/assertions
load ../../../helpers/locations
load ../../../helpers/main
load ../../../helpers/makepkg
load ../../../helpers/mock-loggers

BATS_TEST_NAME_PREFIX="[$( test_suite_name )] "

setup() {
  . "$LIVE_CHECKS/shared_libraries_check.sh"
}

@test "Check logs no error when libtool archive generated by ltmain.sh" {
  create_empty_package $BATS_TEST_TMPDIR

  mkdir -p $BATS_TEST_TMPDIR/usr/lib/app/private/

  sed "s|LINTPKG_LIBDIR|/usr/lib/app/private/|" $TEST_STATICS/shared-libraries/foo-ltmain.la > $BATS_TEST_TMPDIR/usr/lib/app/private/foo.la

  WORKING_DIR=$BATS_TEST_TMPDIR

  run check

  refute_output
}

@test "Check logs no error when libtool archive generated by libtool" {
  create_empty_package $BATS_TEST_TMPDIR

  mkdir -p $BATS_TEST_TMPDIR/usr/lib/app/private/

  sed "s|LINTPKG_LIBDIR|/usr/lib/app/private/|" $TEST_STATICS/shared-libraries/foo-libtool.la > $BATS_TEST_TMPDIR/usr/lib/app/private/foo.la

  WORKING_DIR=$BATS_TEST_TMPDIR

  run check

  refute_output
}
