#!/usr/bin/env bats

TESTSUITE="shared_libraries"

load ../../../helpers/locations
load ../../../helpers/makepkg
load ../../../helpers/mock-loggers

setup() {
  . "$LIVE_CHECKS/shared_libraries_check.sh"
}

@test "[$TESTSUITE] Check logs no error when libtool archive generated by ltmain.sh" {
  BASE=$(create_tmp_dir)

  ! [ -z "$BASE" ]

  create_empty_package $BASE

  mkdir -p $BASE/usr/lib/app/private/

  sed "s|LINTPKG_LIBDIR|/usr/lib/app/private/|" $TEST_STATICS/shared-libraries/foo-ltmain.la > $BASE/usr/lib/app/private/foo.la

  WORKING_DIR=$BASE

  run check

  [ -z "${lines[0]}" ]

  rm -rf "$BASE"
}

@test "[$TESTSUITE] Check logs no error when libtool archive generated by libtool" {
  BASE=$(create_tmp_dir)

  ! [ -z "$BASE" ]

  create_empty_package $BASE

  mkdir -p $BASE/usr/lib/app/private/

  sed "s|LINTPKG_LIBDIR|/usr/lib/app/private/|" $TEST_STATICS/shared-libraries/foo-libtool.la > $BASE/usr/lib/app/private/foo.la

  WORKING_DIR=$BASE

  run check

  [ -z "${lines[0]}" ]

  rm -rf "$BASE"
}
