#!/usr/bin/env bats

load ../../../helpers/assertions
load ../../../helpers/locations
load ../../../helpers/main
load ../../../helpers/makepkg
load ../../../helpers/mock-loggers

BATS_TEST_NAME_PREFIX="[$( test_suite_name )] "

setup() {
  . "$LIVE_CHECKS/shared_libraries_check.sh"
}

@test "Check logs no error when libtool archive generated by ltmain.sh" {
  BASE=$(create_tmp_dir)

  refute [ -z "$BASE" ]

  create_empty_package $BASE

  mkdir -p $BASE/usr/lib/app/private/

  sed "s|LINTPKG_LIBDIR|/usr/lib/app/private/|" $TEST_STATICS/shared-libraries/foo-ltmain.la > $BASE/usr/lib/app/private/foo.la

  WORKING_DIR=$BASE

  run check

  refute_output

  rm -rf "$BASE"
}

@test "Check logs no error when libtool archive generated by libtool" {
  BASE=$(create_tmp_dir)

  refute [ -z "$BASE" ]

  create_empty_package $BASE

  mkdir -p $BASE/usr/lib/app/private/

  sed "s|LINTPKG_LIBDIR|/usr/lib/app/private/|" $TEST_STATICS/shared-libraries/foo-libtool.la > $BASE/usr/lib/app/private/foo.la

  WORKING_DIR=$BASE

  run check

  refute_output

  rm -rf "$BASE"
}
