#!/bin/sh
# SPDX-FileCopyrightText: Copyright 2014  Heinz Wiesinger, Amsterdam, The Netherlands
# SPDX-License-Identifier: BSD-1-Clause

# Verify that installed libtool archives are valid.

check() {
  while read lib && ! [ -z "$lib" ]; do
    BLOCK=$(sed -n '0,/^[^#]/p' "$lib" | sed \$d)

    if [ -z "$(echo "$BLOCK" | grep '^# Generated by' | grep 'libtool')" ]; then
      log_error "invalid-libtool-archive" "$lib"
    fi
  done <<< "$(find "$WORKING_DIR" -type f -name "*.la")"
}

info() {
  if [ "$1" = "invalid-libtool-archive" ]; then
    echo -n "An invalid libtool archive (.la) file will likely result in linking "
    echo "errors for applications that try to use it."
    echo
  fi
}
