.\" Manpage for lintpkg.
.\" SPDX-FileCopyrightText: Copyright 2023  Heinz Wiesinger, Amsterdam, The Netherlands
.\" SPDX-License-Identifier: BSD-1-Clause
.TH man 1 "23 May 2023" "0.9.0" "lintpkg man page"

.SH NAME
lintpkg \- Slackware package linter

.SH SYNOPSIS
lintpkg OPTIONS... [PACKAGE_FILENAME...]

.SH DESCRIPTION
.B lintpkg
is a tool for checking common errors in slackware packages. It can be
used for example to test downloaded packages for common packaging mistakes, or
to check a package you created yourself for things you might have missed. By
default all available checks are performed, but specific checks can be performed
using command line parameters.

.B lintpkg
is heavily based on
.B rpmlint
(https://github.com/rpm-software-management/rpmlint)
and tries to keep compatibility to it where possible in order to make integration
into CI systems that already support rpmlint simple. It does however also try
to keep close to the other pkgtools of slackware.

.SH OPTIONS
.HP
\fB\-c\fR check_name, \fB\-\-check\fR=check_name
.IP
Run only the specified check. This option may be
given multiple times to specify multiple checks
to run.

.HP
\fB\-C\fR check_dir, \fB\-\-checkdir\fR=check_dir
.IP
Specify path to load checks from.

.HP
\fB\-E\fR extract_dir, \fB\-\-extractdir\fR=extract_dir
.IP
Base directory for extracted temporary files.

.HP
\fB\-i\fR, \fB\-\-info\fR
.IP
Display explanations for reported messages.

.HP
\fB\-I\fR messageid, \fB\-\-explain\fR=messageid
.IP
Display explanations for the specified
message identifiers and exit. Multiple
identifiers can be specified by separating
them with commas.

.HP
\fB\-\-ignore\-unused\-overrides\fR
.IP
Don't report overrides that didn't match any
message.

.HP
\fB\-\-overridedir\fR=override_dir
.IP
Specify path to load overrides from, if the
package doesn't ship its own. See OVERRIDES.

.HP
\fB\-\-show\-overrides\fR
.IP
Show overridden messages, together with where
the override came from and the reason for it.

.HP
\fB\-x\fR messageid, \fB\-\-exclude\fR=messageid
.IP
Don't show/count errors for the specified
message identifiers. Multiple identifiers
can be specified by separating them with
commas.

.HP
\fB\-h\fR, \fB\-\-help\fR
.IP
Print a usage message briefly summarizing these command-line options
and the bug-reporting address,
then exit.

.HP
\fB\-V\fR, \fB\-\-version\fR
.IP
Print out the version of
.B lintpkg
that is being run, then exit.
.PP

.SH OVERRIDES
Not every rule applies to every package. Overrides make an exception to a
rule for a package. Overridden rules are not reported and don't count as
errors or warnings, but the summary lists how many errors, warnings and
notices were overridden.

The overrides for a package are read from
.I usr/share/lintpkg/overrides/<package name>
within the package itself. If the package doesn't ship that file, the
overrides shipped with
.B lintpkg
for the package are used instead, from
.I /usr/share/lintpkg/overrides
or the directory given with \fB\-\-overridedir\fR. The two are never combined.

Each line of an overrides file names a rule by its message identifier and,
for rules about a file or directory, the path to override it for, as it will
be installed:
.PP
.nf
.RS
# Binary needs to retain debugging info to be useful
unstripped-binary /usr/bin/foo
.RE
.fi
.PP
For rules that aren't about a path, the argument is optional. Without it, the
rule is overridden for the whole package. With it, the rule is only overridden
for that argument.

A comment directly above an override gives the reason for it, and also
applies to the overrides directly following it, until the next empty line or
comment.

Overrides for rules the package doesn't violate are reported as
.B unused-override
errors. If an override is given more than once, only the first one is used.


.SH "SEE ALSO"
The full documentation for
.B lintpkg
is maintained as a Texinfo manual.  If the
.B info
and
.B lintpkg
programs are properly installed at your site, the command
.IP
.B info lintpkg
.PP
should give you access to the complete manual.
.SH BUGS
https://github.com/pprkut/lintpkg/issues
.SH AUTHOR
Heinz Wiesinger (pprkut@slackware.com)
