# SPDX-FileCopyrightText: Copyright 2026  Heinz Wiesinger, Amsterdam, The Netherlands
# SPDX-License-Identifier: CC0-1.0

name: General Tests
on: [push, pull_request, workflow_dispatch]

permissions: {}

jobs:
  typos:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    continue-on-error: false
    name: "Spellcheck (typos)"
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: typos-action
        uses: crate-ci/typos@00f422f3b19c57bc6338715ebfe3316d38768461 # v1.50.3

  reuse:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: "REUSE compliance"
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@676e2d560c9a403aa252096d99fcab3e1132b0f5 # v6.0.0

  zizmor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: "GitHub Actions analysis (zizmor)"
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@cc914d7f3750a2d13d75c7f184a1060aa0e9d482 # v0.6.4
        with:
          advanced-security: false

  editorconfig:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: "EditorConfig compliance"
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@51f63319f592f97930c73d9c46184d20bd206393 # v3.0.0

      - name: Check files
        run: git ls-files --exclude-standard -z | xargs -0 editorconfig-checker
